# Generated by Django 2.2.13 on 2020-07-07 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syncmgr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='syncentry',
            name='field_map',
        ),
        migrations.AddField(
            model_name='syncentry',
            name='field_map',
            field=models.ManyToManyField(to='syncmgr.FieldMapEntry'),
        ),
    ]
