# Generated by Django 2.2.13 on 2020-07-12 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('syncmgr', '0002_auto_20200707_0548'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncentry',
            name='src_array_key',
            field=models.CharField(default='results', help_text='key used to identify the list of results/entries/items', max_length=16),
        ),
        migrations.AlterField(
            model_name='syncentry',
            name='dst',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dst_sync_entry', to='syncmgr.Service'),
        ),
        migrations.AlterField(
            model_name='syncentry',
            name='field_map',
            field=models.ManyToManyField(blank=True, null=True, to='syncmgr.FieldMapEntry'),
        ),
        migrations.AlterField(
            model_name='syncentry',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='syncmgr.SyncSchedule'),
        ),
        migrations.AlterField(
            model_name='syncentry',
            name='src',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='src_sync_entry', to='syncmgr.Service'),
        ),
    ]
