# Generated by Django 2.2.13 on 2020-07-12 06:20

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('syncmgr', '0003_auto_20200712_0212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='syncentry',
            name='src_array_key',
        ),
        migrations.AlterField(
            model_name='syncentry',
            name='dst_schema',
            field=jsonfield.fields.JSONField(),
        ),
        migrations.AlterField(
            model_name='syncentry',
            name='src_schema',
            field=jsonfield.fields.JSONField(),
        ),
    ]
