# Generated by Django 2.2.13 on 2020-07-12 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syncmgr', '0004_auto_20200712_0620'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldmapentry',
            name='search_field',
            field=models.BooleanField(default=False, help_text="Marks this field as a 'search field.' When syncing, a GET request will first check for an existing entry using search fields. If found, other fields will be updated with a PATCH request. Fields should be marked as a 'search field' if their value is not expected to change."),
        ),
    ]
