# Generated by Django 2.2.13 on 2020-07-13 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syncmgr', '0005_fieldmapentry_search_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncentry',
            name='dst_detail_field',
            field=models.CharField(default='id', help_text="Name of field used for the detail URL. This is usually 'id' butcould be something else like a UUID or name.", max_length=32),
        ),
        migrations.AlterField(
            model_name='fieldmapentry',
            name='search_field',
            field=models.BooleanField(default=False, help_text="Marks this field as a 'search field.' When syncing, a GET request will first check for an existing entry using search fields. If found, other fields will be updated with a PATCH request. Fields should be marked as a 'search field' if their value is not expected to change. If no 'search fields' are available, new entries will be created in the destination service, which could lead to duplicates."),
        ),
    ]
